"""
WatchNexus Gadgets Catalogue
Built-in catalogue of extensions for the WatchNexus media pipeline.
All items have unique names and descriptions original to WatchNexus.

Each gadget has a `supported` flag:
  - True: Backend integration exists, gadget is fully functional
  - False: No backend integration yet, install blocked with explanation
"""

GADGETS_CATALOGUE = [
    # ==================== METADATA PROVIDERS ====================
    # These hook into the existing Marmalade library scanner
    {
        "id": "wn-atlas-metadata",
        "name": "Atlas Metadata Engine",
        "description": "Comprehensive metadata aggregator that cross-references multiple online databases to find the most accurate movie and TV show information including cast, crew, ratings, and plot synopses.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "movies", "tv", "tmdb"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-chronicle-nfo",
        "name": "Chronicle NFO Reader",
        "description": "Parses local .nfo metadata files commonly found alongside media files. Supports both movie and episodic NFO formats including Kodi-style and Plex-style XML schemas.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "nfo", "local", "xml"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-sakura-anidb",
        "name": "Sakura Anime Database",
        "description": "Specialized metadata provider for anime content. Retrieves detailed episode titles, air dates, character information, and series relationships from dedicated anime databases.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "anime", "anidb", "japanese"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-vinyl-musicbrainz",
        "name": "Vinyl Music Identifier",
        "description": "Music metadata provider that identifies tracks using acoustic fingerprinting and cross-references with the MusicBrainz open database for accurate album art, track listings, and artist info.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "music", "musicbrainz", "fingerprint"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-almanac-fanart",
        "name": "Almanac Art Curator",
        "description": "High-resolution artwork provider that sources movie posters, TV show banners, album covers, and artist thumbnails from community-curated fan art repositories.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "artwork", "fanart", "posters"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-lexicon-omdb",
        "name": "Lexicon Rating Aggregator",
        "description": "Fetches audience and critic ratings from multiple sources including Rotten Tomatoes scores, Metacritic averages, and IMDb ratings to provide a unified media quality index.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "metadata_provider",
        "category": "metadata",
        "icon": "",
        "tags": ["metadata", "ratings", "omdb", "reviews"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== SUBTITLE PROVIDERS ====================
    # These integrate with existing subtitle settings
    {
        "id": "wn-babel-opensubtitles",
        "name": "Babel Subtitle Finder",
        "description": "Multi-language subtitle search engine that finds matching subtitles using file hashes for precise results. Supports over 60 languages with automatic encoding detection.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "subtitle_provider",
        "category": "subtitle",
        "icon": "",
        "tags": ["subtitles", "opensubtitles", "multi-language"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-quill-subscene",
        "name": "Quill Subtitle Archive",
        "description": "Community-driven subtitle provider with a vast library of fan-translated subtitles. Excels at finding subtitles for niche content and foreign films.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "subtitle_provider",
        "category": "subtitle",
        "icon": "",
        "tags": ["subtitles", "subscene", "community"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-verse-addic7ed",
        "name": "Verse TV Subtitle Specialist",
        "description": "TV show-focused subtitle provider that specializes in episode-specific translations. Known for fast turnaround on newly aired episodes with high-quality fan translations.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "subtitle_provider",
        "category": "subtitle",
        "icon": "",
        "tags": ["subtitles", "tv-shows", "addic7ed"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-echo-subtitle-sync",
        "name": "Echo Subtitle Synchronizer",
        "description": "Automatic subtitle timing adjustment tool that uses audio analysis to shift subtitle files into perfect sync with your media. Fixes offset issues without manual editing.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "subtitle_provider",
        "category": "subtitle",
        "icon": "",
        "tags": ["subtitles", "sync", "timing", "audio-analysis"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== NOTIFICATION PROVIDERS ====================
    {
        "id": "wn-herald-discord",
        "name": "Herald Discord Notifier",
        "description": "Sends rich notifications to Discord channels via webhooks. Includes media posters, download progress, and library updates with customizable embed formatting.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "notification_provider",
        "category": "notification",
        "icon": "",
        "tags": ["notification", "discord", "webhook"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Notification dispatch engine not yet implemented. This gadget will become functional in a future update.",
    },
    {
        "id": "wn-courier-telegram",
        "name": "Courier Telegram Bot",
        "description": "Telegram bot integration for media notifications. Receive alerts about new library additions, download completions, and system events directly in your Telegram chats.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "notification_provider",
        "category": "notification",
        "icon": "",
        "tags": ["notification", "telegram", "bot"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Notification dispatch engine not yet implemented. This gadget will become functional in a future update.",
    },
    {
        "id": "wn-signal-pushover",
        "name": "Signal Push Notifier",
        "description": "Push notification service that sends alerts to your mobile devices. Supports priority levels, custom sounds, and quiet hours for non-intrusive media notifications.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "notification_provider",
        "category": "notification",
        "icon": "",
        "tags": ["notification", "pushover", "mobile"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Notification dispatch engine not yet implemented. This gadget will become functional in a future update.",
    },
    {
        "id": "wn-dispatch-email",
        "name": "Dispatch Email Reporter",
        "description": "Email notification service with HTML-formatted media reports. Sends daily or weekly digests of new content, download activity, and system health summaries.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "notification_provider",
        "category": "notification",
        "icon": "",
        "tags": ["notification", "email", "smtp", "digest"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Notification dispatch engine not yet implemented. This gadget will become functional in a future update.",
    },
    {
        "id": "wn-beacon-slack",
        "name": "Beacon Slack Messenger",
        "description": "Slack workspace integration for team-based media management. Posts updates to channels about library changes, download queues, and user activity.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "notification_provider",
        "category": "notification",
        "icon": "",
        "tags": ["notification", "slack", "workspace"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Notification dispatch engine not yet implemented. This gadget will become functional in a future update.",
    },

    # ==================== THEME PROVIDERS ====================
    # These hook into the existing ThemeContext
    {
        "id": "wn-obsidian-theme",
        "name": "Obsidian Dark Suite",
        "description": "Deep black AMOLED-optimized dark theme with sharp contrasts and vivid accent colors. Designed for home theater environments with minimal light bleed.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "theme_provider",
        "category": "theme",
        "icon": "",
        "tags": ["theme", "dark", "amoled", "cinema"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-arctic-theme",
        "name": "Arctic Light Canvas",
        "description": "Clean, bright theme optimized for daytime use with soft shadows and gentle transitions. Features a paper-white background with muted blue accents.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "theme_provider",
        "category": "theme",
        "icon": "",
        "tags": ["theme", "light", "clean", "minimal"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-sakura-bloom-theme",
        "name": "Sakura Bloom",
        "description": "Japanese-inspired theme with soft pink gradients, cherry blossom accents, and elegant typography. Perfect for anime collections with a serene aesthetic.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "theme_provider",
        "category": "theme",
        "icon": "",
        "tags": ["theme", "anime", "japanese", "pink"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-retro-crt-theme",
        "name": "Retro CRT Terminal",
        "description": "Nostalgic green-on-black terminal aesthetic with scanline effects and phosphor glow. A unique throwback theme for tech enthusiasts and retro media collectors.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "theme_provider",
        "category": "theme",
        "icon": "",
        "tags": ["theme", "retro", "terminal", "green"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== VIDEO ADD-ONS ====================
    {
        "id": "wn-prism-iptv",
        "name": "Prism IPTV Client",
        "description": "Full-featured IPTV player supporting M3U playlists and EPG guides. Watch live television streams with channel grouping, favorites, and automatic EPG updates.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "stream_provider",
        "category": "video",
        "icon": "",
        "tags": ["video", "iptv", "live-tv", "m3u", "epg"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-mosaic-youtube",
        "name": "Mosaic Video Browser",
        "description": "Browse and stream web video content directly within WatchNexus. Supports playlist imports, subscription feeds, and background playback with queue management.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "stream_provider",
        "category": "video",
        "icon": "",
        "tags": ["video", "streaming", "web"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Web video streaming engine not yet implemented. Requires backend integration with video extraction services.",
    },
    {
        "id": "wn-meridian-upnp",
        "name": "Meridian UPnP/DLNA Gateway",
        "description": "Universal Plug and Play media renderer and server. Stream content from and to any DLNA-compatible device on your network including smart TVs, gaming consoles, and NAS devices.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "stream_provider",
        "category": "video",
        "icon": "",
        "tags": ["video", "upnp", "dlna", "network", "streaming"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "DLNA/UPnP server not yet integrated. Requires system-level network service implementation.",
    },
    {
        "id": "wn-archive-trakt",
        "name": "Archive Watch Tracker",
        "description": "Synchronizes your watch history, ratings, and collections with the Trakt.tv service. Enables cross-platform tracking so your progress follows you everywhere.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "video",
        "icon": "",
        "tags": ["video", "trakt", "history", "sync", "ratings"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Trakt.tv API integration not yet implemented. Requires OAuth setup and sync engine.",
    },

    # ==================== AUDIO ADD-ONS ====================
    {
        "id": "wn-cadence-radio",
        "name": "Cadence Internet Radio",
        "description": "Internet radio tuner with thousands of stations organized by genre, country, and quality. Features station search, favorites, and now-playing metadata display.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "stream_provider",
        "category": "audio",
        "icon": "",
        "tags": ["audio", "radio", "streaming", "internet-radio"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Internet radio streaming requires integration with a radio directory API (e.g., Radio Browser). Coming in a future update.",
    },
    {
        "id": "wn-rhythm-podcast",
        "name": "Rhythm Podcast Manager",
        "description": "Podcast subscription and playback manager. Subscribe to RSS feeds, auto-download new episodes, track listening progress, and organize shows by category.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "stream_provider",
        "category": "audio",
        "icon": "",
        "tags": ["audio", "podcast", "rss", "subscription"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Podcast RSS parser and episode manager not yet implemented. Coming in a future update.",
    },
    {
        "id": "wn-sonata-lyrics",
        "name": "Sonata Lyrics Display",
        "description": "Real-time synchronized lyrics display for music playback. Fetches lyrics from multiple sources and displays them karaoke-style timed to your music.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "audio",
        "icon": "",
        "tags": ["audio", "lyrics", "music", "karaoke"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Lyrics API integration not yet implemented. Requires connection to a lyrics database service.",
    },

    # ==================== INDEXER PROVIDERS ====================
    # These hook into the existing Compote indexer system
    {
        "id": "wn-compass-torznab",
        "name": "Compass Torznab Gateway",
        "description": "Universal indexer gateway implementing the Torznab API specification. Connect to any Torznab-compatible indexer for automated media discovery and release searching.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "indexer_provider",
        "category": "indexer",
        "icon": "",
        "tags": ["indexer", "torznab", "api", "search"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-scope-newznab",
        "name": "Scope Newznab Connector",
        "description": "Usenet indexer integration supporting the Newznab API. Search NZB indexers for binary releases with quality filtering and automatic category matching.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "indexer_provider",
        "category": "indexer",
        "icon": "",
        "tags": ["indexer", "newznab", "usenet", "nzb"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-rover-rss",
        "name": "Rover RSS Feed Monitor",
        "description": "RSS/Atom feed monitor for tracking new releases from custom sources. Supports regex filtering, category rules, and automatic download triggers.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "indexer_provider",
        "category": "indexer",
        "icon": "",
        "tags": ["indexer", "rss", "atom", "feed", "monitor"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== SYSTEM TOOLS ====================
    {
        "id": "wn-sentinel-health",
        "name": "Sentinel Health Monitor",
        "description": "Real-time system health dashboard showing CPU usage, memory consumption, disk space, network throughput, and service uptime. Triggers alerts when thresholds are exceeded.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "scheduled_task",
        "category": "system",
        "icon": "",
        "tags": ["system", "health", "monitor", "dashboard"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-vault-backup",
        "name": "Vault Database Backup",
        "description": "Automated backup scheduler for your WatchNexus database and configuration. Creates timestamped snapshots with configurable retention policies and optional cloud sync.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "scheduled_task",
        "category": "system",
        "icon": "",
        "tags": ["system", "backup", "database", "scheduler"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-curator-cleanup",
        "name": "Curator Library Janitor",
        "description": "Automated library maintenance tool that detects orphaned metadata, removes stale entries, cleans up empty directories, and optimizes database performance.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "scheduled_task",
        "category": "system",
        "icon": "",
        "tags": ["system", "cleanup", "maintenance", "optimization"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-warden-auth-ldap",
        "name": "Warden LDAP Authenticator",
        "description": "Enterprise LDAP/Active Directory authentication provider. Allows organizations to use their existing directory services for WatchNexus user authentication and group management.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "auth_provider",
        "category": "system",
        "icon": "",
        "tags": ["system", "auth", "ldap", "active-directory", "enterprise"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "LDAP authentication engine not yet implemented. Requires directory service connector.",
    },

    # ==================== PICTURE/GALLERY ====================
    {
        "id": "wn-gallery-viewer",
        "name": "Gallery Photo Viewer",
        "description": "Local photo library viewer with slideshow capabilities, EXIF data display, and thumbnail generation. Supports JPEG, PNG, RAW, and HEIF formats.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "image",
        "icon": "",
        "tags": ["image", "gallery", "photos", "slideshow"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Photo scanning and thumbnail generation engine not yet implemented. Requires image processing backend.",
    },

    # ==================== GAME INTEGRATIONS ====================
    {
        "id": "wn-arcade-retroarch",
        "name": "Arcade Retro Launcher",
        "description": "Retro gaming integration that launches RetroArch cores for classic console emulation. Browse your ROM collection with box art and launch games directly from the WatchNexus interface.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "game",
        "icon": "",
        "tags": ["game", "retro", "emulation", "retroarch"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "WatchNexus does not include a game emulation engine. RetroArch integration requires RetroArch to be installed separately on the host system, which is outside the scope of this media server.",
    },

    # ==================== SCREENSAVER ====================
    {
        "id": "wn-aurora-screensaver",
        "name": "Aurora Ambient Display",
        "description": "Beautiful ambient screensaver that displays rotating artwork from your media library with smooth transitions, clock overlay, and now-playing information.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "screensaver",
        "icon": "",
        "tags": ["screensaver", "ambient", "artwork", "display"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Screensaver rendering engine not yet implemented. Requires idle detection and fullscreen artwork rotation.",
    },

    # ==================== WEATHER ====================
    {
        "id": "wn-forecast-weather",
        "name": "Forecast Weather Widget",
        "description": "Dashboard weather widget showing current conditions and multi-day forecasts. Customizable location settings with animated weather icons and sunrise/sunset times.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "weather",
        "icon": "",
        "tags": ["weather", "widget", "dashboard", "forecast"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Weather API integration not yet implemented. Requires connection to a weather data provider.",
    },

    # ==================== PROGRAM/UTILITY ====================
    {
        "id": "wn-forge-transcoder",
        "name": "Forge Media Transcoder",
        "description": "On-demand media transcoding engine for converting files between formats. Supports hardware acceleration (NVENC, QSV, VAAPI) for efficient format conversion and resolution scaling.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "program",
        "icon": "",
        "tags": ["program", "transcoding", "ffmpeg", "conversion"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-matrix-remote",
        "name": "Matrix Remote Control Server",
        "description": "Remote control server allowing smartphones and tablets to control WatchNexus playback. Includes virtual D-pad, media browser, and voice search capabilities.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "program",
        "icon": "",
        "tags": ["program", "remote", "control", "mobile"],
        "source": "builtin",
        "status": "available",
        "supported": False,
        "compatibility_note": "Remote control WebSocket server not yet implemented. Requires real-time communication layer.",
    },
    {
        "id": "wn-nexus-api-bridge",
        "name": "Nexus External API Bridge",
        "description": "Exposes a compatibility API layer allowing third-party apps designed for other media servers to connect to WatchNexus. Provides Jellyfin-compatible endpoints for broad client support.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "program",
        "icon": "",
        "tags": ["program", "api", "compatibility", "jellyfin"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== SERVICE/AUTOMATION ====================
    {
        "id": "wn-shepherd-watchdog",
        "name": "Shepherd Service Watchdog",
        "description": "Process monitor that watches WatchNexus services and automatically restarts crashed components. Logs failure events and sends notifications on repeated failures.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "scheduled_task",
        "category": "service",
        "icon": "",
        "tags": ["service", "watchdog", "monitoring", "auto-restart"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-cron-scheduler",
        "name": "Clockwork Task Scheduler",
        "description": "Advanced cron-style task scheduler for automating library scans, backups, metadata refreshes, and custom scripts on configurable time-based schedules.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "scheduled_task",
        "category": "service",
        "icon": "",
        "tags": ["service", "scheduler", "cron", "automation"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== CONTEXT MENU ====================
    {
        "id": "wn-shortcut-context",
        "name": "Shortcut Context Actions",
        "description": "Adds customizable context menu actions to media items. Right-click to quickly mark as watched, add to playlists, refresh metadata, or trigger downloads.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "context",
        "icon": "",
        "tags": ["context", "menu", "shortcuts", "actions"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },

    # ==================== RESOURCE PACKS ====================
    {
        "id": "wn-atlas-language-pack",
        "name": "Atlas Language Pack",
        "description": "Extended language support with community-contributed translations for over 30 languages. Covers all UI strings, error messages, and media category labels.",
        "version": "1.0.0",
        "author": "WatchNexus Community",
        "plugin_type": "general",
        "category": "resource",
        "icon": "",
        "tags": ["resource", "language", "translation", "i18n"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
    {
        "id": "wn-icon-pack-neon",
        "name": "Neon Icon Collection",
        "description": "Vibrant neon-styled icon pack for the WatchNexus interface. Replaces default icons with glowing, cyberpunk-inspired alternatives for a unique visual experience.",
        "version": "1.0.0",
        "author": "WatchNexus Team",
        "plugin_type": "general",
        "category": "resource",
        "icon": "",
        "tags": ["resource", "icons", "neon", "visual"],
        "source": "builtin",
        "status": "available",
        "supported": True,
        "compatibility_note": "",
    },
]

# Category configuration for the catalogue
CATALOGUE_CATEGORIES = {
    "metadata": {"label": "Metadata Providers", "description": "Fetch and manage media information from online databases", "count": 0},
    "subtitle": {"label": "Subtitle Services", "description": "Find and synchronize subtitles for your media", "count": 0},
    "notification": {"label": "Notification Services", "description": "Get alerts about media events on your favorite platforms", "count": 0},
    "theme": {"label": "Visual Themes", "description": "Customize the look and feel of WatchNexus", "count": 0},
    "video": {"label": "Video Extensions", "description": "Stream, track, and manage video content", "count": 0},
    "audio": {"label": "Audio Extensions", "description": "Radio, podcasts, and music enhancements", "count": 0},
    "indexer": {"label": "Indexer Connectors", "description": "Connect to content discovery services", "count": 0},
    "system": {"label": "System Tools", "description": "Health monitoring, backups, and authentication", "count": 0},
    "image": {"label": "Picture Add-ons", "description": "Photo galleries and image management", "count": 0},
    "game": {"label": "Gaming", "description": "Retro gaming and game library integration", "count": 0},
    "screensaver": {"label": "Screensavers", "description": "Ambient displays and idle screen themes", "count": 0},
    "weather": {"label": "Weather", "description": "Weather widgets and forecasts", "count": 0},
    "program": {"label": "Programs & Utilities", "description": "Transcoding, remote control, and API tools", "count": 0},
    "service": {"label": "Background Services", "description": "Watchdogs, schedulers, and automation", "count": 0},
    "context": {"label": "Context Menus", "description": "Quick actions and shortcuts", "count": 0},
    "resource": {"label": "Resource Packs", "description": "Languages, icons, and visual assets", "count": 0},
}

# Count items per category
for item in GADGETS_CATALOGUE:
    cat = item.get("category", "other")
    if cat in CATALOGUE_CATEGORIES:
        CATALOGUE_CATEGORIES[cat]["count"] += 1


def get_catalogue():
    """Return the full gadgets catalogue."""
    return GADGETS_CATALOGUE


def get_catalogue_categories():
    """Return categories with counts."""
    return CATALOGUE_CATEGORIES


def search_catalogue(query="", category=None, plugin_type=None):
    """Search the catalogue by query, category, or type."""
    results = GADGETS_CATALOGUE
    
    if category:
        results = [g for g in results if g["category"] == category]
    
    if plugin_type:
        results = [g for g in results if g["plugin_type"] == plugin_type]
    
    if query:
        q = query.lower()
        results = [g for g in results if 
            q in g["name"].lower() or 
            q in g["description"].lower() or
            any(q in tag for tag in g.get("tags", []))
        ]
    
    return results
