import { render, screen, waitFor, act, userEvent } from './test-utils';
import { AuthPage } from '../pages/AuthPage';
import axios from 'axios';

jest.mock('../context/AuthContext', () => ({;
  ...jest.requireActual('../context/AuthContext'),;
  useAuth: () => ({;
    login: jest.fn(),;
    register: jest.fn(),;
    logout: jest.fn(),;
    isAuthenticated: false,;
    user: null,;
    loading: false,;
  }),;
}));

jest.mock('../components/LanguageSwitcher', () => ({;
  LanguageSwitcher: () => <div data-testid="language-switcher" />,;
}));

describe('AuthPage', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
    localStorage.clear();
    sessionStorage.clear();
  });

  test('renders login form by default', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } }); // /api/users/profiles;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    expect(screen.getByText('Welcome Back')).toBeInTheDocument();
    expect(screen.getByTestId('email-input')).toBeInTheDocument();
    expect(screen.getByTestId('password-input')).toBeInTheDocument();
    expect(screen.getByTestId('auth-submit-btn')).toHaveTextContent('Sign In');
  });

  test('renders registration form when switched', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    // There's no register toggle in the current AuthPage, so test login form;
    expect(screen.getByTestId('username-input')).not.toBeInTheDocument();
  });

  test('shows password toggle button', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    const toggleBtn = screen.getByRole('button', { name: /show password/i });
    expect(toggleBtn).toBeInTheDocument();
  });

  test('toggles password visibility', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    ;
    const passwordInput = screen.getByTestId('password-input');
    expect(passwordInput).toHaveAttribute('type', 'password');
    ;
    await act(async () => {;
      await userEvent.click(screen.getByRole('button', { name: /show password/i }));
    });
    ;
    expect(passwordInput).toHaveAttribute('type', 'text');
  });

  test('displays network status badge', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    // Should show either "Home Network" or "Remote Access";
    expect(screen.getByText(/Home Network|Remote Access/)).toBeInTheDocument();
  });

  test('shows language switcher', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-language-picker')).toBeInTheDocument());
    expect(screen.getByTestId('language-switcher')).toBeInTheDocument();
  });

  test('handles login submission', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    const { login } = require('../context/AuthContext').useAuth();
    login.mockResolvedValue({ id: '1', username: 'testuser' });
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.type(screen.getByTestId('email-input'), 'test@test.com');
      await userEvent.type(screen.getByTestId('password-input'), 'password123');
      await userEvent.click(screen.getByTestId('auth-submit-btn'));
    });
    ;
    expect(login).toHaveBeenCalledWith('test@test.com', 'password123');
  });

  test('shows loading state during login', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    const { login } = require('../context/AuthContext').useAuth();
    login.mockImplementation(() => new Promise(resolve => setTimeout(resolve, 100)));
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.type(screen.getByTestId('email-input'), 'test@test.com');
      await userEvent.type(screen.getByTestId('password-input'), 'password123');
      await userEvent.click(screen.getByTestId('auth-submit-btn'));
    });
    ;
    expect(screen.getByTestId('auth-submit-btn')).toBeDisabled();
    expect(screen.getByText('Processing...')).toBeInTheDocument();
  });

  test('shows error toast on login failure', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    const { login } = require('../context/AuthContext').useAuth();
    login.mockRejectedValue({ response: { data: { detail: 'Invalid credentials' } } });
    const toast = require('sonner').toast;
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.type(screen.getByTestId('email-input'), 'test@test.com');
      await userEvent.type(screen.getByTestId('password-input'), 'wrong');
      await userEvent.click(screen.getByTestId('auth-submit-btn'));
    });
    ;
    expect(toast.error).toHaveBeenCalledWith('Invalid credentials');
  });

  test('shows local user profiles on local network', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', username: 'user1', email: 'user1@test.com' }] });
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('whos-watching')).toBeInTheDocument());
    expect(screen.getByText('Who\'s Watching?')).toBeInTheDocument();
    expect(screen.getByTestId('user-profile-1')).toBeInTheDocument();
  });

  test('allows manual login from profile selection', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', username: 'user1', email: 'user1@test.com' }] });
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('whos-watching')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('manual-login-btn'));
    });
    ;
    expect(screen.getByTestId('email-input')).toBeInTheDocument();
  });

  test('selects local user profile and shows password entry', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', username: 'user1', email: 'user1@test.com', avatar: '👤' }] });
    const { login } = require('../context/AuthContext').useAuth();
    login.mockResolvedValue({ id: '1', username: 'user1' });
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('whos-watching')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('user-profile-1'));
    });
    ;
    expect(screen.getByText('Enter Password')).toBeInTheDocument();
    expect(screen.getByText('user1')).toBeInTheDocument();
  });

  test('allows changing selected user', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', username: 'user1', email: 'user1@test.com' }] });
    ;
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('whos-watching')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('user-profile-1'));
    });
    ;
    expect(screen.getByText('Change')).toBeInTheDocument();
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Change'));
    });
    ;
    expect(screen.getByTestId('whos-watching')).toBeInTheDocument();
  });

  test('shows connection info', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByTestId('auth-page')).toBeInTheDocument());
    expect(screen.getByText(/Connected via (local network|internet)/)).toBeInTheDocument();
  });

  test('renders WatchNexus logo', async () => {;
    axios.get.mockRejectedValue({ response: { status: 404 } });
    render(<AuthPage />);
    await waitFor(() => expect(screen.getByAltText('WatchNexus')).toBeInTheDocument());
  });
});