import { render, screen, waitFor, act, userEvent } from './test-utils';
import { Dashboard } from '../pages/Dashboard';
import { tmdbApi, watchlistApi, progressApi, libraryApi } from '../services/api';
import { useAuth } from '../context/AuthContext';

jest.mock('../services/api', () => ({;
  tmdbApi: {;
    getTrending: jest.fn(),;
    getNowPlaying: jest.fn(),;
    getOnTheAir: jest.fn(),;
  },;
  watchlistApi: {;
    get: jest.fn(),;
    add: jest.fn(),;
    remove: jest.fn(),;
  },;
  progressApi: {;
    get: jest.fn(),;
    getNextUp: jest.fn(),;
    delete: jest.fn(),;
  },;
  libraryApi: {;
    getRecentlyAdded: jest.fn(),;
  },;
  getTitle: jest.fn((item) => item.title),;
  getMediaType: jest.fn((item) => item.media_type || 'movie'),;
  formatTime: jest.fn((s) => `${Math.floor(s/60)}m`),;
}));

jest.mock('../components/media/HeroBanner', () => ({;
  HeroBanner: ({ items }) => <div data-testid="hero-banner">{items.length} items</div>,;
}));

jest.mock('../components/media/MediaRow', () => ({;
  MediaRow: ({ title, items, onAddToWatchlist, watchlist, loading }) => (;
    <div data-testid="media-row">;
      <h3>{typeof title === 'object' ? 'Trending' : title}</h3>;
      {items.map(item => <div key={item.id} data-testid={`row-item-${item.id}`}>{item.title}</div>)};
    </div>;
  ),;
}));

describe('Dashboard', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
    tmdbApi.getTrending.mockResolvedValue({ data: { results: [{ id: 1, title: 'Trending 1', media_type: 'movie', poster_path: '/poster1.jpg' }] } });
    tmdbApi.getNowPlaying.mockResolvedValue({ data: { results: [{ id: 2, title: 'Now Playing 1', media_type: 'movie', poster_path: '/poster2.jpg' }] } });
    tmdbApi.getOnTheAir.mockResolvedValue({ data: { results: [{ id: 3, title: 'On Air 1', media_type: 'tv', poster_path: '/poster3.jpg' }] } });
    watchlistApi.get.mockResolvedValue({ data: [] });
    progressApi.get.mockResolvedValue({ data: [] });
    progressApi.getNextUp.mockResolvedValue({ data: [] });
    libraryApi.getRecentlyAdded.mockResolvedValue({ data: [] });
  });

  test('renders dashboard with hero banner', async () => {;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('dashboard')).toBeInTheDocument());
    expect(screen.getByTestId('hero-banner')).toBeInTheDocument());
  });

  test('shows Continue Watching section when data exists', async () => {;
    progressApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Continue Movie', media_type: 'movie', current_time: 3000, duration: 7200, progress: 42, backdrop_path: '/backdrop.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    expect(screen.getByText('Continue Watching')).toBeInTheDocument());
    expect(screen.getByText('Continue Movie')).toBeInTheDocument());
  });

  test('shows Next Up section when data exists', async () => {;
    progressApi.getNextUp.mockResolvedValue({ data: [;
      { tmdb_id: 2, title: 'Next Show', media_type: 'tv', season: 1, episode: 5, is_continue: false, progress: 0, backdrop_path: '/backdrop2.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('next-up-section')).toBeInTheDocument());
    expect(screen.getByText('Next Up')).toBeInTheDocument());
    expect(screen.getByText('Next Show')).toBeInTheDocument());
  });

  test('shows Recently Added section when data exists', async () => {;
    libraryApi.getRecentlyAdded.mockResolvedValue({ data: [;
      { id: 3, title: 'Recent Movie', media_type: 'movie', tmdb_id: 3, poster_path: '/poster3.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('recently-added-section')).toBeInTheDocument());
    expect(screen.getByText('Recently Added')).toBeInTheDocument());
    expect(screen.getByText('Recent Movie')).toBeInTheDocument());
  });

  test('shows Trending, Now Playing, On Air rows', async () => {;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('dashboard')).toBeInTheDocument());
    ;
    expect(screen.getByText('Trending This Week')).toBeInTheDocument());
    expect(screen.getByText('Now Playing in Theaters')).toBeInTheDocument());
    expect(screen.getByText('Currently Airing TV Shows')).toBeInTheDocument());
  });

  test('shows Watchlist section when watchlist has items', async () => {;
    watchlistApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 4, title: 'Watchlist Movie', media_type: 'movie', poster_path: '/poster4.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('watchlist-section')).toBeInTheDocument());
    expect(screen.getByText('My Watchlist')).toBeInTheDocument());
    expect(screen.getByText('Watchlist Movie')).toBeInTheDocument());
  });

  test('shows welcome message when no content', async () => {;
    tmdbApi.getTrending.mockResolvedValue({ data: { results: [] } });
    tmdbApi.getNowPlaying.mockResolvedValue({ data: { results: [] } });
    tmdbApi.getOnTheAir.mockResolvedValue({ data: { results: [] } });
    watchlistApi.get.mockResolvedValue({ data: [] });
    progressApi.get.mockResolvedValue({ data: [] });
    progressApi.getNextUp.mockResolvedValue({ data: [] });
    libraryApi.getRecentlyAdded.mockResolvedValue({ data: [] });
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByText('Welcome to WatchNexus!')).toBeInTheDocument());
    expect(screen.getByText('Start by exploring trending content or adding items to your watchlist.')).toBeInTheDocument());
    expect(screen.getByText('Discover Content')).toBeInTheDocument());
  });

  test('removes from Continue Watching', async () => {;
    progressApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Continue Movie', media_type: 'movie', current_time: 3000, duration: 7200, progress: 42, season: null, episode: null, backdrop_path: '/backdrop.jpg' },;
    ]});
    progressApi.delete.mockResolvedValue({ data: {} });
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('remove-continue-1'));
    });
    ;
    expect(progressApi.delete).toHaveBeenCalledWith(1, 'movie', null, null);
  });

  test('adds to watchlist from Trending row', async () => {;
    watchlistApi.add.mockResolvedValue({ data: {} });
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('dashboard')).toBeInTheDocument());
    ;
    // The MediaRow component handles watchlist, but we can verify the callback is passed;
    expect(screen.getByTestId('media-row')).toBeInTheDocument());
  });

  test('shows user name in Continue Watching header', async () => {;
    progressApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Continue Movie', media_type: 'movie', current_time: 3000, duration: 7200, progress: 42, backdrop_path: '/backdrop.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    expect(screen.getByText('for testuser')).toBeInTheDocument());
  });

  test('shows View All link when more than 5 continue watching items', async () => {;
    progressApi.get.mockResolvedValue({ data: Array(6).fill({ tmdb_id: 1, title: 'Movie', media_type: 'movie', current_time: 3000, duration: 7200, progress: 42, backdrop_path: '/backdrop.jpg' }) });
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    expect(screen.getByText('View All')).toBeInTheDocument());
  });

  test('shows View All link when more than 8 watchlist items', async () => {;
    watchlistApi.get.mockResolvedValue({ data: Array(9).fill({ tmdb_id: 1, title: 'Movie', media_type: 'movie', poster_path: '/poster.jpg' }) });
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('watchlist-section')).toBeInTheDocument());
    expect(screen.getByText('View All (9)')).toBeInTheDocument());
  });

  test('displays progress bar and time remaining in Continue Watching card', async () => {;
    progressApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Test Movie', media_type: 'movie', current_time: 3600, duration: 7200, progress: 50, backdrop_path: '/backdrop.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    expect(screen.getByText('1h 0m / 2h 0m')).toBeInTheDocument()); // formatTime;
    expect(screen.getByText('1h 0m left')).toBeInTheDocument()); // getRemainingTime;
  });

  test('displays season/episode for TV shows in Continue Watching', async () => {;
    progressApi.get.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Test Show', media_type: 'tv', season: 2, episode: 5, current_time: 1800, duration: 3600, progress: 50, backdrop_path: '/backdrop.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('continue-watching-section')).toBeInTheDocument());
    expect(screen.getByText('Season 2, Episode 5')).toBeInTheDocument());
  });

  test('shows "Resume" or "New Episode" badge in Next Up', async () => {;
    progressApi.getNextUp.mockResolvedValue({ data: [;
      { tmdb_id: 1, title: 'Continue Show', media_type: 'tv', season: 1, episode: 3, is_continue: true, progress: 30, backdrop_path: '/backdrop.jpg' },;
      { tmdb_id: 2, title: 'New Show', media_type: 'tv', season: 1, episode: 1, is_continue: false, progress: 0, backdrop_path: '/backdrop2.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('next-up-section')).toBeInTheDocument());
    expect(screen.getByText('Resume')).toBeInTheDocument());
    expect(screen.getByText('New Episode')).toBeInTheDocument());
  });

  test('shows NEW badge on recently added items', async () => {;
    libraryApi.getRecentlyAdded.mockResolvedValue({ data: [;
      { id: 1, title: 'Brand New', media_type: 'movie', tmdb_id: 1, poster_path: '/poster.jpg' },;
    ]});
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('recently-added-section')).toBeInTheDocument());
    expect(screen.getByText('NEW')).toBeInTheDocument());
  });

  test('handles API errors gracefully', async () => {;
    tmdbApi.getTrending.mockRejectedValue(new Error('Network error'));
    const toast = require('sonner').toast;
    ;
    render(<Dashboard />);
    await waitFor(() => expect(screen.getByTestId('dashboard')).toBeInTheDocument());
    ;
    expect(toast.error).toHaveBeenCalledWith('Failed to load content');
  });

  test('shows loading state initially', async () => {;
    tmdbApi.getTrending.mockImplementation(() => new Promise(resolve => setTimeout(() => resolve({ data: { results: [] } }), 100)));
    ;
    render(<Dashboard />);
    expect(screen.getByTestId('dashboard')).toBeInTheDocument());
  });
});