import { render, screen, waitFor, act, userEvent } from './test-utils';
import { LibraryPage } from '../pages/LibraryPage';
import { marmaladeStatus, marmaladeLibrary, marmaladeMedia } from '../services/marmaladeApi';
import { useConfirm } from '../hooks/use-confirm';

jest.mock('../services/marmaladeApi', () => ({;
  marmaladeStatus: { getStatus: jest.fn() },;
  marmaladeLibrary: { getLibraries: jest.fn(), addLibrary: jest.fn(), removeLibrary: jest.fn(), scanLibrary: jest.fn(), refreshMetadata: jest.fn() },;
  marmaladeMedia: { getMedia: jest.fn(), getRecent: jest.fn(), getTVSeriesGrouped: jest.fn(), search: jest.fn() },;
  formatDuration: jest.fn((s) => `${Math.floor(s/60)}m`),;
  formatFileSize: jest.fn((b) => `${Math.round(b/1024/1024)}MB`),;
}));

jest.mock('../hooks/use-confirm', () => ({;
  useConfirm: () => ({;
    confirm: jest.fn().mockResolvedValue(true),;
    ConfirmDialog: () => null,;
  }),;
}));

jest.mock('../components/MediaFolderDropdown', () => ({;
  MediaFolderDropdown: () => <div data-testid="media-folder-dropdown" />,;
}));

jest.mock('../components/FolderBrowser', () => () => <div data-testid="folder-browser" />);

describe('LibraryPage', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
    marmaladeStatus.getStatus.mockResolvedValue({ data: { status: 'running', libraries: 2, media_files: 100 } });
    marmaladeLibrary.getLibraries.mockResolvedValue({ data: [;
      { id: '1', name: 'Movies', path: '/movies', media_type: 'movies', item_count: 50 },;
      { id: '2', name: 'TV Shows', path: '/tv', media_type: 'tv', item_count: 50 },;
    ]});
    marmaladeMedia.getRecent.mockResolvedValue({ data: [;
      { id: '1', title: 'Movie 1', media_type: 'movie', poster_url: '/poster1.jpg', year: 2023 },;
      { id: '2', title: 'Show 1', media_type: 'episode', poster_url: '/poster2.jpg', year: 2022 },;
    ]});
    marmaladeMedia.getMedia.mockResolvedValue({ data: [] });
    marmaladeMedia.getTVSeriesGrouped.mockResolvedValue({ data: [] });
  });

  test('renders library page with header', async () => {;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    expect(screen.getByText('Library')).toBeInTheDocument();
    expect(screen.getByText('Your media collection')).toBeInTheDocument();
  });

  test('shows server status', async () => {;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByText('Marmalade')).toBeInTheDocument());
    expect(screen.getByText('2 libraries')).toBeInTheDocument();
    expect(screen.getByText('100 files')).toBeInTheDocument();
  });

  test('shows libraries grid', async () => {;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByText('Libraries')).toBeInTheDocument());
    expect(screen.getByText('Movies')).toBeInTheDocument();
    expect(screen.getByText('TV Shows')).toBeInTheDocument());
    expect(screen.getByText('50 items')).toBeInTheDocument(); // Both have 50;
  });

  test('shows recently added section', async () => {;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByText('Recently Added')).toBeInTheDocument());
    expect(screen.getByText('Movie 1')).toBeInTheDocument();
    expect(screen.getByText('Show 1')).toBeInTheDocument());
  });

  test('adds new library', async () => {;
    marmaladeLibrary.addLibrary.mockResolvedValue({ data: { id: '3', name: 'Music', path: '/music', media_type: 'music' } });
    marmaladeLibrary.scanLibrary.mockResolvedValue({ data: { new: 10 } });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Add Library'));
    });
    ;
    expect(screen.getByPlaceholderText('My Movies')).toBeInTheDocument();
    ;
    await act(async () => {;
      await userEvent.type(screen.getByPlaceholderText('My Movies'), 'Music');
      await userEvent.type(screen.getByPlaceholderText('/media/movies'), '/music');
      await userEvent.selectOptions(screen.getByRole('combobox'), 'music');
      await userEvent.click(screen.getByText('Add & Scan'));
    });
    ;
    expect(marmaladeLibrary.addLibrary).toHaveBeenCalledWith('Music', '/music', 'music');
  });

  test('scans library', async () => {;
    marmaladeLibrary.scanLibrary.mockResolvedValue({ data: { new: 5, updated: 2, removed: 1 } });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('Scan for new files'));
    });
    ;
    expect(marmaladeLibrary.scanLibrary).toHaveBeenCalledWith('1');
  });

  test('refreshes metadata', async () => {;
    marmaladeLibrary.refreshMetadata.mockResolvedValue({ data: { refreshed: 10, total: 50 } });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('Refresh metadata from TMDB'));
    });
    ;
    expect(marmaladeLibrary.refreshMetadata).toHaveBeenCalledWith('1');
  });

  test('removes library with confirmation', async () => {;
    marmaladeLibrary.removeLibrary.mockResolvedValue({ data: {} });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('Delete library'));
    });
    ;
    expect(marmaladeLibrary.removeLibrary).toHaveBeenCalledWith('1');
  });

  test('searches media', async () => {;
    marmaladeMedia.search.mockResolvedValue({ data: [{ id: '3', title: 'Search Result', media_type: 'movie' }] });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.type(screen.getByPlaceholderText('Search your library...'), 'Search');
      await userEvent.click(screen.getByText('Search'));
    });
    ;
    expect(marmaladeMedia.search).toHaveBeenCalledWith('Search');
  });

  test('toggles view mode between All and Series', async () => {;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    expect(screen.getByText('All')).toBeInTheDocument();
    expect(screen.getByText('Series')).toBeInTheDocument();
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Series'));
    });
    ;
    expect(screen.getByText('No TV Series Found')).toBeInTheDocument();
  });

  test('expands TV series when clicked', async () => {;
    marmaladeMedia.getTVSeriesGrouped.mockResolvedValue({ data: [{;
      series_name: 'Test Show',;
      poster_url: '/poster.jpg',;
      seasons: [{;
        season_number: 1,;
        episode_count: 10,;
        episodes: [{ id: 'ep1', title: 'Episode 1', episode_number: 1, size: 1000000000, watched: false }],;
      }],;
      total_episodes: 10,;
    }]});
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Series'));
    });
    ;
    await waitFor(() => expect(screen.getByText('Test Show')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Test Show'));
    });
    ;
    expect(screen.getByText('Season 1')).toBeInTheDocument();
    expect(screen.getByText('Episode 1')).toBeInTheDocument());
  });

  test('shows empty state when no libraries', async () => {;
    marmaladeLibrary.getLibraries.mockResolvedValue({ data: [] });
    marmaladeMedia.getRecent.mockResolvedValue({ data: [] });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByText('No libraries configured')).toBeInTheDocument());
    expect(screen.getByText('Add a library to start scanning your media')).toBeInTheDocument());
  });

  test('shows empty state when no media found', async () => {;
    marmaladeMedia.getMedia.mockResolvedValue({ data: [] });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Movies'));
    });
    ;
    expect(screen.getByText('No Media Found')).toBeInTheDocument());
  });

  test('auto-selects media type based on folder name', async () => {;
    marmaladeLibrary.addLibrary.mockResolvedValue({ data: { id: '3' } });
    marmaladeLibrary.scanLibrary.mockResolvedValue({ data: { new: 0 } });
    ;
    render(<LibraryPage />);
    await waitFor(() => expect(screen.getByTestId('library-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Add Library'));
      await userEvent.type(screen.getByPlaceholderText('My Movies'), '');
      await userEvent.type(screen.getByPlaceholderText('/media/movies'), '/media/tv-shows');
      // The component auto-detects from folder name;
      await userEvent.click(screen.getByText('Add & Scan'));
    });
    ;
    expect(marmaladeLibrary.addLibrary).toHaveBeenCalledWith(;
      expect.any(String),;
      '/media/tv-shows',;
      'tv';
    );
  });
});