import { render, screen, waitFor, act, userEvent } from './test-utils';
import { LiveTVPage } from '../pages/LiveTVPage';
import axios from 'axios';

jest.mock('../hooks/use-confirm', () => ({;
  useConfirm: () => ({;
    confirm: jest.fn().mockResolvedValue(true),;
    ConfirmDialog: () => null,;
  }),;
}));

describe('LiveTVPage', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
    axios.get;
      .mockResolvedValue({ data: { total_channels: 10, total_groups: 2, favorites_count: 3 } }) // stats;
      .mockResolvedValue({ data: [{ id: '1', name: 'Source 1', url: 'http://test.m3u', channel_count: 50 }] }) // sources;
      .mockResolvedValue({ data: [;
        { id: 'ch1', name: 'Channel 1', group: 'News', logo: '/logo1.png', stream_url: 'http://stream1', is_favorite: false },;
        { id: 'ch2', name: 'Channel 2', group: 'Sports', logo: '/logo2.png', stream_url: 'http://stream2', is_favorite: true },;
      ]}) // channels;
      .mockResolvedValue({ data: ['News', 'Sports'] }); // groups;
    axios.post.mockResolvedValue({ data: {} });
    axios.delete.mockResolvedValue({ data: {} });
  });

  test('renders Live TV page with header', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    expect(screen.getByText('Live TV')).toBeInTheDocument();
    expect(screen.getByText('IPTV channels and live streams')).toBeInTheDocument();
  });

  test('shows stats in header', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByText('10 channels')).toBeInTheDocument());
    expect(screen.getByText('2 groups')).toBeInTheDocument();
    expect(screen.getByText('3 favorites')).toBeInTheDocument();
  });

  test('shows three tabs: Channels, Guide, Sources', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByText('Channels')).toBeInTheDocument());
    expect(screen.getByText('Guide')).toBeInTheDocument();
    expect(screen.getByText('Sources')).toBeInTheDocument();
  });

  test('displays channels in grid view by default', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByText('Channel 1')).toBeInTheDocument());
    expect(screen.getByText('Channel 2')).toBeInTheDocument());
    expect(screen.getByText('News')).toBeInTheDocument());
    expect(screen.getByText('Sports')).toBeInTheDocument());
  });

  test('switches to list view', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('List'));
    });
    ;
    // In list view, channels should still be visible;
    expect(screen.getByText('Channel 1')).toBeInTheDocument();
  });

  test('filters channels by group', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.selectOptions(screen.getByRole('combobox'), 'News');
    });
    ;
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/channels'), expect.objectContaining({ params: expect.objectContaining({ group: 'News' }) }));
  });

  test('filters channels by search query', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.type(screen.getByPlaceholderText('Search channels...'), 'Channel 1');
    });
    ;
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/channels'), expect.objectContaining({ params: expect.objectContaining({ search: 'Channel 1' }) }));
  });

  test('toggles favorites only', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Favorites'));
    });
    ;
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/channels'), expect.objectContaining({ params: expect.objectContaining({ favorites_only: true }) }));
  });

  test('adds new IPTV source', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Add Source'));
    });
    ;
    await act(async () => {;
      await userEvent.type(screen.getByPlaceholderText('My IPTV'), 'My Source');
      await userEvent.type(screen.getByPlaceholderText('http://example.com/playlist.m3u'), 'http://test.m3u');
      await userEvent.click(screen.getByText('Add Source'));
    });
    ;
    expect(axios.post).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/sources'), null, expect.objectContaining({ params: expect.objectContaining({ name: 'My Source', url: 'http://test.m3u' }) }));
  });

  test('refreshes IPTV source', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Guide'));
      await userEvent.click(screen.getByText('Sources'));
    });
    ;
    await waitFor(() => expect(screen.getByText('Source 1')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('Refresh'));
    });
    ;
    expect(axios.post).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/sources/1/refresh'), null, expect.anything());
  });

  test('deletes IPTV source with confirmation', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Guide'));
      await userEvent.click(screen.getByText('Sources'));
    });
    ;
    await waitFor(() => expect(screen.getByText('Source 1')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTitle('Delete'));
    });
    ;
    expect(axios.delete).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/sources/1'), expect.anything());
  });

  test('exports M3U playlist', async () => {;
    axios.get.mockResolvedValueOnce({ data: { content: '#EXTM3U\n#EXTINF:-1,Channel 1\nhttp://stream1', filename: 'playlist.m3u' } });
    ;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Export M3U'));
    });
    ;
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/export'), expect.objectContaining({ params: expect.objectContaining({ favorites_only: false }) }));
  });

  test('toggles channel favorite', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      // Click favorite button on first channel;
      await userEvent.click(screen.getByTestId('live-tv-page').querySelectorAll('button[aria-label]')[0]);
    });
    ;
    expect(axios.post).toHaveBeenCalledWith(expect.stringContaining('/api/iptv/channels/ch1/favorite'), null, expect.anything());
  });

  test('opens channel player modal', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Channel 1'));
    });
    ;
    expect(screen.getByText('Channel 1')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /close/i })).toBeInTheDocument();
  });

  test('shows EPG Guide tab', async () => {;
    axios.get.mockResolvedValueOnce({ data: [] }); // EPG data for channel;
    ;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Guide'));
    });
    ;
    expect(screen.getByText('TV Guide')).toBeInTheDocument();
    expect(screen.getByText('Channels')).toBeInTheDocument();
    expect(screen.getByText('Now')).toBeInTheDocument();
  });

  test('navigates EPG date', async () => {;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Guide'));
      await userEvent.click(screen.getByTitle('Previous day'));
    });
    ;
    // Date should change;
  });

  test('shows program details on click', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: 'prog1', title: 'News Program', start: new Date().toISOString(), end: new Date(Date.now() + 3600000).toISOString(), duration_minutes: 60, description: 'Latest news' }] });
    ;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Guide'));
    });
    ;
    // Click on a program in the EPG;
    await waitFor(() => expect(screen.getByText('News Program')).toBeInTheDocument());
  });

  test('shows empty state when no sources', async () => {;
    axios.get.mockResolvedValueOnce({ data: { total_channels: 0, total_groups: 0, favorites_count: 0 } });
      .mockResolvedValueOnce({ data: [] });
      .mockResolvedValueOnce({ data: [] });
      .mockResolvedValueOnce({ data: [] });
    ;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Sources'));
    });
    ;
    expect(screen.getByText('No IPTV Sources')).toBeInTheDocument());
    expect(screen.getByText('Add an M3U playlist URL to get started')).toBeInTheDocument());
  });

  test('shows empty state when no channels', async () => {;
    axios.get.mockResolvedValueOnce({ data: { total_channels: 0, total_groups: 0, favorites_count: 0 } });
      .mockResolvedValueOnce({ data: [{ id: '1', name: 'Source 1', url: 'http://test.m3u' }] });
      .mockResolvedValueOnce({ data: [] });
      .mockResolvedValueOnce({ data: [] });
    ;
    render(<LiveTVPage />);
    await waitFor(() => expect(screen.getByTestId('live-tv-page')).toBeInTheDocument());
    ;
    expect(screen.getByText('No Channels')).toBeInTheDocument());
    expect(screen.getByText('Add an IPTV source (M3U playlist) to get started')).toBeInTheDocument());
  });
});