import { render, screen, waitFor, act, userEvent } from './test-utils';
import { SettingsPage } from '../pages/SettingsPage';
import axios from 'axios';

// Mock all settings sub-components;
jest.mock('../components/settings', () => ({;
  GeneralSettings: ({ settings, setSettings, onSave, saving, onOpenFileBrowser }) => (;
    <div data-testid="general-settings">;
      <h2>General Settings</h2>;
      <button data-testid="save-general" onClick={onSave} disabled={saving}>;
        {saving ? 'Saving...' : 'Save'};
      </button>;
      <button data-testid="open-browser" onClick={() => onOpenFileBrowser('download_path')}>;
        Browse;
      </button>;
    </div>;
  ),;
  UsersSettings: ({ users, loadingUsers, showAddUser, setShowAddUser, newUser, setNewUser, savingUser, editingUser, setEditingUser, onAddUser, onUpdateUser, onDeleteUser, currentUserId }) => (;
    <div data-testid="users-settings">;
      <h2>Users Settings</h2>;
      {showAddUser && <div data-testid="add-user-form">Add User Form</div>};
      <button data-testid="add-user-btn" onClick={() => setShowAddUser(true)}>Add User</button>;
      {users.map(u => (;
        <div key={u.id} data-testid={`user-${u.id}`}>;
          <span>{u.username}</span>;
          <button onClick={() => onUpdateUser(u.id, { username: 'updated' })}>Update</button>;
          <button onClick={() => onDeleteUser(u.id)}>Delete</button>;
        </div>;
      ))};
    </div>;
  ),;
  LibrarySettings: ({ libraries, loadingLibraries, scanningLibrary, showAddLibrary, setShowAddLibrary, newLibrary, setNewLibrary, onAddLibrary, onDeleteLibrary, onScanLibrary, onOpenFileBrowser, librarySubTab, setLibrarySubTab, manualImportPath, setManualImportPath, manualImportFiles, onManualImportScan, onImportFiles }) => (;
    <div data-testid="library-settings">;
      <h2>Library Settings</h2>;
      <button data-testid="add-library-btn" onClick={() => setShowAddLibrary(true)}>Add Library</button>;
      {libraries.map(l => (;
        <div key={l.id} data-testid={`library-${l.id}`}>;
          <span>{l.name}</span>;
          <button onClick={() => onScanLibrary(l.id)} disabled={scanningLibrary === l.id}>Scan</button>;
          <button onClick={() => onDeleteLibrary(l.id)}>Delete</button>;
        </div>;
      ))};
    </div>;
  ),;
  MediaHealthSettings: () => <div data-testid="media-health-settings">Media Health Settings</div>,;
  CrumbsSettings: () => <div data-testid="crumbs-settings">API Management</div>,;
  PlaybackSettings: () => <div data-testid="playback-settings">Playback Settings</div>,;
  FFmpegSettings: () => <div data-testid="ffmpeg-settings">FFmpeg Settings</div>,;
  QualityProfilesSettings: () => <div data-testid="quality-profiles-settings">Quality Profiles</div>,;
  IndexerSettings: () => <div data-testid="indexer-settings">Indexer Settings</div>,;
  DownloadSettings: () => <div data-testid="download-settings">Download Settings</div>,;
  IPTVSettings: () => <div data-testid="iptv-settings">IPTV Settings</div>,;
  StreamingSettings: () => <div data-testid="streaming-settings">Streaming Settings</div>,;
  SubtitleSettings: () => <div data-testid="subtitle-settings">Subtitle Settings</div>,;
  GelatinSettings: () => <div data-testid="gelatin-settings">External Access</div>,;
  ThemeForgeSettings: () => <div data-testid="theme-forge-settings">Theme Forge</div>,;
  PluginsSettings: () => <div data-testid="plugins-settings">Gadgets</div>,;
  ZestSettings: () => <div data-testid="zest-settings">Logs & Health</div>,;
  MaintenanceSettings: () => <div data-testid="maintenance-settings">Maintenance</div>,;
  AboutSettings: () => <div data-testid="about-settings">About & Releases</div>,;
  ActivationSettings: () => <div data-testid="activation-settings">License Activation</div>,;
  UpdateSettings: () => <div data-testid="update-settings">Software Updates</div>,;
}));

jest.mock('../components/settings/UpdateSettings', () => ({;
  UpdateSettings: () => <div data-testid="update-settings">Software Updates</div>,;
}));

jest.mock('../components/settings/ZestSettings', () => ({;
  ZestSettings: () => <div data-testid="zest-settings">Logs & Health</div>,;
}));

jest.mock('../components/settings/CrumbsSettings', () => ({;
  CrumbsSettings: () => <div data-testid="crumbs-settings">API Management</div>,;
}));

jest.mock('../components/settings/FFmpegSettings', () => ({;
  FFmpegSettings: () => <div data-testid="ffmpeg-settings">FFmpeg Settings</div>,;
}));

jest.mock('../hooks/use-confirm', () => ({;
  useConfirm: () => ({;
    confirm: jest.fn().mockResolvedValue(true),;
    ConfirmDialog: () => null,;
  }),;
}));

jest.mock('../components/FolderBrowser', () => () => <div data-testid="folder-browser" />);

describe('SettingsPage', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
    localStorage.clear();
    sessionStorage.clear();
    ;
    // Mock default API responses;
    axios.get;
      .mockResolvedValue({ data: {} }) // settingsApi.get;
      .mockResolvedValue({ data: [] }) // /api/users, /api/marmalade/libraries;
      .mockResolvedValue({ data: [] }); // any other GET;
    axios.post.mockResolvedValue({ data: {} });
    axios.put.mockResolvedValue({ data: {} });
    axios.delete.mockResolvedValue({ data: {} });
  });

  test('renders settings page with sidebar navigation', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    expect(screen.getByText('Settings')).toBeInTheDocument();
    expect(screen.getByText('Configure WatchNexus')).toBeInTheDocument());
  });

  test('shows all navigation sections', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    // Core Settings;
    expect(screen.getByTestId('settings-nav-general')).toHaveTextContent('General');
    expect(screen.getByTestId('settings-nav-users')).toHaveTextContent('Users');
    expect(screen.getByTestId('settings-nav-library')).toHaveTextContent('Media Libraries');
    expect(screen.getByTestId('settings-nav-media-health')).toHaveTextContent('Media Health');
    ;
    // Integrations;
    expect(screen.getByTestId('settings-nav-integrations')).toHaveTextContent('API Management');
    expect(screen.getByTestId('settings-nav-indexers')).toHaveTextContent('Indexers');
    expect(screen.getByTestId('settings-nav-download')).toHaveTextContent('Download Client');
    ;
    // Playback & Streaming;
    expect(screen.getByTestId('settings-nav-playback')).toHaveTextContent('Playback');
    expect(screen.getByTestId('settings-nav-ffmpeg')).toHaveTextContent('FFmpeg');
    expect(screen.getByTestId('settings-nav-quality-profiles')).toHaveTextContent('Quality Profiles');
    expect(screen.getByTestId('settings-nav-iptv')).toHaveTextContent('IPTV');
    expect(screen.getByTestId('settings-nav-streaming')).toHaveTextContent('Streaming Services');
    expect(screen.getByTestId('settings-nav-subtitles')).toHaveTextContent('Subtitles');
    ;
    // Advanced;
    expect(screen.getByTestId('settings-nav-gelatin')).toHaveTextContent('External Access');
    expect(screen.getByTestId('settings-nav-theme-forge')).toHaveTextContent('Theme Forge');
    expect(screen.getByTestId('settings-nav-plugins')).toHaveTextContent('Gadgets');
    expect(screen.getByTestId('settings-nav-logs')).toHaveTextContent('Logs & Health');
    expect(screen.getByTestId('settings-nav-maintenance')).toHaveTextContent('Maintenance');
    ;
    // About;
    expect(screen.getByTestId('settings-nav-activation')).toHaveTextContent('License Activation');
    expect(screen.getByTestId('settings-nav-updates')).toHaveTextContent('Updates');
    expect(screen.getByTestId('settings-nav-about')).toHaveTextContent('About & Releases');
  });

  test('renders General settings by default', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('general-settings')).toBeInTheDocument());
    expect(screen.getByText('General Settings')).toBeInTheDocument();
  });

  test('navigates to Users section when clicked', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-users'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('users-settings')).toBeInTheDocument());
    expect(screen.getByText('Users Settings')).toBeInTheDocument();
  });

  test('navigates to Library section when clicked', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-library'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('library-settings')).toBeInTheDocument());
    expect(screen.getByText('Library Settings')).toBeInTheDocument();
  });

  test('navigates to Activation section when clicked', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-activation'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('activation-settings')).toBeInTheDocument());
    expect(screen.getByText('License Activation')).toBeInTheDocument();
  });

  test('shows active section indicator', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    const generalBtn = screen.getByTestId('settings-nav-general');
    expect(generalBtn).toHaveStyle({ backgroundColor: expect.stringContaining('var(--primary') });
  });

  test('fetches users on mount', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', username: 'admin', email: 'admin@test.com', role: 'admin' }] });
    ;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-users'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('users-settings')).toBeInTheDocument());
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/users'));
  });

  test('fetches libraries on mount', async () => {;
    axios.get.mockResolvedValueOnce({ data: [{ id: '1', name: 'Movies', path: '/movies', media_type: 'movies', item_count: 100 }] });
    ;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-library'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('library-settings')).toBeInTheDocument());
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/marmalade/libraries'));
  });

  test('shows file browser modal when triggered', async () => {;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('settings-nav-general'));
    });
    ;
    await waitFor(() => expect(screen.getByTestId('general-settings')).toBeInTheDocument());
    await act(async () => {;
      await userEvent.click(screen.getByTestId('open-browser'));
    });
    ;
    expect(screen.getByTestId('folder-browser')).toBeInTheDocument();
  });

  test('renders all sub-sections correctly', async () => {;
    const sections = [;
      { id: 'settings-nav-media-health', testId: 'media-health-settings', title: 'Media Health Settings' },;
      { id: 'settings-nav-integrations', testId: 'crumbs-settings', title: 'API Management' },;
      { id: 'settings-nav-playback', testId: 'playback-settings', title: 'Playback Settings' },;
      { id: 'settings-nav-ffmpeg', testId: 'ffmpeg-settings', title: 'FFmpeg Settings' },;
      { id: 'settings-nav-quality-profiles', testId: 'quality-profiles-settings', title: 'Quality Profiles' },;
      { id: 'settings-nav-indexers', testId: 'indexer-settings', title: 'Indexer Settings' },;
      { id: 'settings-nav-download', testId: 'download-settings', title: 'Download Settings' },;
      { id: 'settings-nav-iptv', testId: 'iptv-settings', title: 'IPTV Settings' },;
      { id: 'settings-nav-streaming', testId: 'streaming-settings', title: 'Streaming Settings' },;
      { id: 'settings-nav-subtitles', testId: 'subtitle-settings', title: 'Subtitle Settings' },;
      { id: 'settings-nav-gelatin', testId: 'gelatin-settings', title: 'External Access' },;
      { id: 'settings-nav-theme-forge', testId: 'theme-forge-settings', title: 'Theme Forge' },;
      { id: 'settings-nav-plugins', testId: 'plugins-settings', title: 'Gadgets' },;
      { id: 'settings-nav-logs', testId: 'zest-settings', title: 'Logs & Health' },;
      { id: 'settings-nav-maintenance', testId: 'maintenance-settings', title: 'Maintenance' },;
      { id: 'settings-nav-about', testId: 'about-settings', title: 'About & Releases' },;
      { id: 'settings-nav-updates', testId: 'update-settings', title: 'Software Updates' },;
    ];
    ;
    for (const section of sections) {;
      jest.clearAllMocks();
      render(<SettingsPage />);
      await waitFor(() => expect(screen.getByTestId('settings-page')).toBeInTheDocument());
      ;
      await act(async () => {;
        await userEvent.click(screen.getByTestId(section.id));
      });
      ;
      await waitFor(() => expect(screen.getByTestId(section.testId)).toBeInTheDocument());
      expect(screen.getByText(section.title)).toBeInTheDocument();
    };
  });

  test('saves general settings', async () => {;
    axios.put.mockResolvedValueOnce({ data: {} });
    const toast = require('sonner').toast;
    ;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('general-settings')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('save-general'));
    });
    ;
    expect(toast.success).toHaveBeenCalledWith('Settings saved successfully');
  });

  test('shows error toast on save failure', async () => {;
    axios.put.mockRejectedValueOnce(new Error('Failed'));
    const toast = require('sonner').toast;
    ;
    render(<SettingsPage />);
    await waitFor(() => expect(screen.getByTestId('general-settings')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('save-general'));
    });
    ;
    expect(toast.error).toHaveBeenCalledWith('Failed to save settings');
  });
});