import { render, screen, waitFor, act, userEvent } from './test-utils';
import { TierGate } from '../components/TierGate';
import { useLicense } from '../context/LicenseContext';
import { useNavigate } from 'react-router-dom';

jest.mock('../context/LicenseContext', () => ({;
  ...jest.requireActual('../context/LicenseContext'),;
  useLicense: () => ({;
    isRouteUnlocked: jest.fn(),;
    getRouteRequiredTier: jest.fn(),;
    ROUTE_MODULE_MAP: { '/security': 'security', '/vpn': 'vpn', '/indexers': 'compote' },;
  }),;
  ROUTE_MODULE_MAP: { '/security': 'security', '/vpn': 'vpn', '/indexers': 'compote' },;
}));

jest.mock('react-router-dom', () => ({;
  ...jest.requireActual('react-router-dom'),;
  useNavigate: () => jest.fn(),;
}));

jest.mock('../components/layout/Layout', () => ({;
  Layout: ({ children }) => <div data-testid="layout">{children}</div>,;
}));

jest.mock('lucide-react', () => ({;
  Lock: () => <svg data-testid="lock-icon" />,;
  Zap: () => <svg data-testid="zap-icon" />,;
  Crown: () => <svg data-testid="crown-icon" />,;
  ArrowRight: () => <svg data-testid="arrow-right-icon" />,;
}));

jest.mock('../components/ui/button', () => ({;
  Button: ({ children, onClick, disabled, className, style, 'data-testid': testid, ...props }) => (;
    <button onClick={onClick} disabled={disabled} className={className} style={style} data-testid={testid} {...props}>;
      {children};
    </button>;
  ),;
}));

const TestComponent = ({ path = '/security' }) => (;
  <TierGate path={path}>;
    <div data-testid="protected-content">Protected Content</div>;
  </TierGate>;
);

describe('TierGate', () => {;
  beforeEach(() => {;
    jest.clearAllMocks();
  });

  test('renders children when route is unlocked', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => true),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByTestId('protected-content')).toBeInTheDocument());
    expect(screen.queryByTestId('tier-gate')).not.toBeInTheDocument());
  });

  test('shows tier gate when route is locked (Pro required)', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByTestId('tier-gate')).toBeInTheDocument());
    expect(screen.getByText('Pro Feature')).toBeInTheDocument());
    expect(screen.getByText('compote')).toBeInTheDocument());
    expect(screen.getByText('requires a WatchNexus Pro license')).toBeInTheDocument());
    expect(screen.getByTestId('tier-gate-activate-btn')).toHaveTextContent('Enter Serial Number');
  });

  test('shows tier gate when route is locked (Ultra required)', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'ultra'),;
      ROUTE_MODULE_MAP: { '/security': 'security' },;
    });
    ;
    render(<TestComponent path="/security" />);
    await waitFor(() => expect(screen.getByTestId('tier-gate')).toBeInTheDocument());
    expect(screen.getByText('Ultra Feature')).toBeInTheDocument());
    expect(screen.getByText('security')).toBeInTheDocument());
    expect(screen.getByText('requires a WatchNexus Ultra license')).toBeInTheDocument());
  });

  test('navigates to settings activation on button click', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    const mockNavigate = jest.fn();
    require('react-router-dom').useNavigate.mockReturnValue(mockNavigate);
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByTestId('tier-gate-activate-btn')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByTestId('tier-gate-activate-btn'));
    });
    ;
    expect(mockNavigate).toHaveBeenCalledWith('/settings', { state: { section: 'activation' } });
  });

  test('shows go back button', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    const mockNavigate = jest.fn();
    require('react-router-dom').useNavigate.mockReturnValue(mockNavigate);
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByText('Go Back')).toBeInTheDocument());
    ;
    await act(async () => {;
      await userEvent.click(screen.getByText('Go Back'));
    });
    ;
    expect(mockNavigate).toHaveBeenCalledWith(-1);
  });

  test('shows correct feature descriptions for Pro', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByText('Unlock automation, analytics, scheduled tasks, advanced search, and network tools.')).toBeInTheDocument());
  });

  test('shows correct feature descriptions for Ultra', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'ultra'),;
      ROUTE_MODULE_MAP: { '/security': 'security' },;
    });
    ;
    render(<TestComponent path="/security" />);
    await waitFor(() => expect(screen.getByText('Unlock the full suite: security, media processing, notifications, disc ripping, and all premium gadgets.')).toBeInTheDocument());
  });

  test('shows lock icon', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByTestId('lock-icon')).toBeInTheDocument());
  });

  test('shows Zap icon for Pro tier', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/indexers': 'compote' },;
    });
    ;
    render(<TestComponent path="/indexers" />);
    await waitFor(() => expect(screen.getByTestId('zap-icon')).toBeInTheDocument());
  });

  test('shows Crown icon for Ultra tier', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'ultra'),;
      ROUTE_MODULE_MAP: { '/security': 'security' },;
    });
    ;
    render(<TestComponent path="/security" />);
    await waitFor(() => expect(screen.getByTestId('crown-icon')).toBeInTheDocument());
  });

  test('uses module name from ROUTE_MODULE_MAP', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: { '/custom': 'custom-module' },;
    });
    ;
    render(<TestComponent path="/custom" />);
    await waitFor(() => expect(screen.getByText('custom-module')).toBeInTheDocument());
  });

  test('falls back to "this feature" for unknown routes', async () => {;
    const { useLicense } = require('../context/LicenseContext');
    useLicense.mockReturnValue({;
      isRouteUnlocked: jest.fn(() => false),;
      getRouteRequiredTier: jest.fn(() => 'pro'),;
      ROUTE_MODULE_MAP: {},;
    });
    ;
    render(<TestComponent path="/unknown" />);
    await waitFor(() => expect(screen.getByText('this feature')).toBeInTheDocument());
  });
});